src/Entity/DadoPessoal.php
<?php

namespace App\Entity;

use App\Validator\Constraints\DateTime;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * DadoPessoal
 *
 * @ORM\Table(name="DBPETINFOSD.TB_DADO_PESSOAL")
 * @ORM\Entity(repositoryClass="App\Repository\DadoPessoalRepository")
 */
class DadoPessoal extends AbstractEntity
{
    use \App\Traits\DataInclusaoTrait;
    
    /**
     * @var int
     * 
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\Column(name="CO_SEQ_DADO_PESSOAL", type="integer", unique=true)
     * @ORM\SequenceGenerator(sequenceName="DBPETINFOSD.SQ_DADOPESSOAL_COSEQDADOPESSOA", allocationSize=1, initialValue=1)
     */
    private $coSeqDadoPessoal;

    /**
     * @var PessoaFisica
     *
     * @ORM\OneToOne(targetEntity="App\Entity\PessoaFisica")
     * @ORM\JoinColumn(name="NU_CPF", referencedColumnName="NU_CPF")
     */
    private $pessoaFisica;

    /**
     * @var string
     *
     * @ORM\Column(name="CO_AGENCIA", type="string", nullable=false)
     */
    private $agencia;

    /**
     * @var Banco
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Banco")
     * @ORM\JoinColumn(name="CO_BANCO", referencedColumnName="CO_BANCO", nullable=false)
     */
    private $banco;

    /**
     * @var string
     *
     * @ORM\Column(name="CO_CONTA", type="string", nullable=true)
     */
    private $conta;

    /**
     * @param PessoaFisica $pessoaFisica
     * @param $agencia
     * @param $banco
     */
    public function __construct(
        PessoaFisica $pessoaFisica,
        $banco = null,
        $agencia = null,
        $conta = null
    ) {
        $this->pessoaFisica     = $pessoaFisica;
        $this->banco            = $banco;
        $this->agencia          = $agencia;
        $this->conta            = $conta;
        $this->stRegistroAtivo  = 'S';
        $this->dtInclusao       = new \DateTime();
    }

    /**
     * Get coSeqDadoPessoal
     *
     * @return int
     */
    public function getCoSeqDadoPessoal()
    {
        return $this->coSeqDadoPessoal;
    }

    /**
     * Get PessoaFisica
     *
     * @return PessoaFisica
     */
    public function getPessoaFisica()
    {
        return $this->pessoaFisica;
    }

    public function getDtNascimento() {
        $this->getPessoaFisica()->getDtNascimento();
    }

    /**
     * Get conta
     *
     * @return string
     */
    public function getConta()
    {
        return $this->conta;
    }

    /**
     * Get agencia
     *
     * @return string
     */
    public function getAgencia()
    {
        return $this->agencia;
    }

    /**
     * Get banco
     *
     * @return string
     */
    public function getBanco()
    {
        return $this->banco;
    }

    /**
     * @param string $agencia
     * @return DadoPessoal
     */
    public function setAgencia($agencia)
    {
        $this->agencia = $agencia;
        return $this;
    }

    /**
     * @param $banco
     * @return DadoPessoal
     */
    public function setBanco($banco)
    {
        $this->banco = $banco;
        return $this;
    }

    /**
     * @param string $conta
     * @return DadoPessoal
     */
    public function setConta($conta)
    {
        $this->conta = $conta;
        return $this;
    }

}

src/Entity/Usuario.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Usuario
 *
 * @ORM\Table(name="DBPETINFOSD.TB_USUARIO")
 * @ORM\Entity(repositoryClass="App\Repository\UsuarioRepository")
 */
class Usuario extends AbstractEntity implements UserInterface, \Serializable
{
    use \App\Traits\DeleteLogicoTrait;
    use \App\Traits\DataInclusaoTrait;
    
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\Column(name="CO_SEQ_USUARIO", type="integer")
     * @ORM\SequenceGenerator(sequenceName="DBPETINFOSD.SQ_USUARIO_COSEQUSUARIO", allocationSize=1, initialValue=1)
     */
    private $coSeqUsuario;

    /**
     * @var PessoaFisica
     * 
     * @ORM\OneToOne(targetEntity="App\Entity\PessoaFisica", inversedBy="usuario")
     * @ORM\JoinColumn(name="NU_CPF", referencedColumnName="NU_CPF")
     */
    private $pessoaFisica;
    
    /**
     * @var string
     *
     * @ORM\Column(name="DS_LOGIN", type="string", length=40, unique=true)
     */
    private $dsLogin;

    /**
     * @var string
     *
     * @ORM\Column(name="DS_SENHA", type="string", length=64)
     */
    private $dsSenha;

    /**
     * 
     * @param PessoaFisica $pessoaFisica
     * @param string $dsLogin
     * @param string $dsSenha
     */
    public function __construct($pessoaFisica, $dsLogin, $dsSenha)
    {
        $this->pessoaFisica = $pessoaFisica;
        $this->dsLogin = $dsLogin;
        $this->dsSenha = $dsSenha;
        $this->stRegistroAtivo = 'S';
        $this->dtInclusao = new \DateTime();
    }
    
    /**
     * Get coSeqUsuario
     *
     * @return int
     */
    public function getCoSeqUsuario()
    {
        return $this->coSeqUsuario;
    }
    
    /**
     * @param PessoaFisica
     */
    public function setPessoaFisica($pessoaFisica)
    {
        $this->pessoaFisica = $pessoaFisica;
        return $this;
    }
    
    /**
     * 
     */
    public function getPessoaFisica()
    {
        return $this->pessoaFisica;
    }

    /**
     * Set dsLogin
     *
     * @param string $dsLogin
     *
     * @return Usuario
     */
    public function setDsLogin($dsLogin)
    {
        $this->dsLogin = $dsLogin;

        return $this;
    }

    /**
     * Get dsLogin
     *
     * @return string
     */
    public function getDsLogin()
    {
        return $this->dsLogin;
    }

    /**
     * Set dsSenha
     *
     * @param string $dsSenha
     *
     * @return Usuario
     */
    public function setDsSenha($dsSenha)
    {
        $this->dsSenha = $dsSenha;

        return $this;
    }

    /**
     * Get dsSenha
     *
     * @return string
     */
    public function getDsSenha()
    {
        return $this->dsSenha;
    }

    /**
     * @return string
     */
    public function getStRegistroAtivo()
    {
        return $this->stRegistroAtivo;
    }

    /**
     * @param string $stRegistroAtivo
     */
    public function setStRegistroAtivo($stRegistroAtivo)
    {
        $this->stRegistroAtivo = $stRegistroAtivo;
    }

    /**
     * @inheritdoc
     */
    public function eraseCredentials(){}

    /**
     * @inheritdoc
     */
    public function getPassword()
    {
        return $this->getDsSenha();
    }

    /**
     * @inheritdoc
     */
    public function getRoles()
    {
        $pessoasPerfis = $this->getPessoaFisica()->getPessoasPerfis();
        
        $roles = array('ROLE_USER');
        
        foreach ($pessoasPerfis as $pessoaPerfil) {
            $roles[] = $pessoaPerfil->getPerfil()->getRole();
        }
        
        return array_unique($roles);
    }

    /**
     * @inheritdoc
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * @inheritdoc
     */
    public function getUsername()
    {
        return $this->getDsLogin();
    }

    /**
     * @inheritdoc
     */
    public function serialize()
    {
        return serialize(
            array(
                $this->coSeqUsuario,
                $this->dsLogin,
                $this->dsSenha
            )
        );
    }

    /**
     * @inheritdoc
     */
    public function unserialize($serialized)
    {
        list (
            $this->coSeqUsuario,
            $this->dsLogin,
            $this->dsSenha
        ) = unserialize($serialized);
    }
    
    /**
     * @param PessoaPerfil $pessoaPerfil
     * @param Projeto|null $projeto
     * @throws \DomainException
     */
    public function checkIdentidade(PessoaPerfil $pessoaPerfil, Projeto $projeto = null)
    {
        $hasAccess = false;
       
        foreach ($this->getPessoaFisica()->getPessoasPerfisAtivos() as $item) {
            if ($item->getCoSeqPessoaPerfil() == $pessoaPerfil->getCoSeqPessoaPerfil()) {
                if ($projeto) {
                    foreach ($item->getProjetosPessoasAtivos() as $item) {
                        if ($item->getProjeto()->getCoSeqProjeto() == $projeto->getCoSeqProjeto()) {
                            $hasAccess = true;
                        }
                    }
                } else {
                    $hasAccess = true;
                }
            }
        }
        
        if (!$hasAccess) {
            throw new \DomainException('Identidade inválida');
        }
    }
}

src/Controller/ArquivoRetornoCadastroController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\ParameterBag;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use League\Tactician\Bundle\Middleware\InvalidCommandException;
use App\CommandBus\RecepcionarArquivoRetornoCadastroCommand;
use App\Form\RecepcionarArquivoRetornoCadastroType;
use App\Form\FiltroRelatorioRetornoCriacaoContaType;
use App\Form\ConsultarRetornosCadastroType;
use App\Exception\UnexpectedCommandBehaviorException;
use App\Entity\RetornoCriacaoConta;
use App\Cpb\DicionarioCpb;

/**
 * @Security("is_granted('ADMINISTRADOR')")
 */
final class ArquivoRetornoCadastroController extends ControllerAbstract
{
    use \App\Traits\DownloadResponseTrait;
    
    /**
     * 
     * @param Request $request
     * @return Response
     * 
     * @Route("arquivo-retorno-cadastro", name="arquivo_retorno_cadastro", options={"expose"=true})
     * @Method({"GET"})
     */
    public function index(Request $request)
    {
        $form = $this->createForm(ConsultarRetornosCadastroType::class);
        $form->handleRequest($request);

        $pagination = null;
        
        if ($form->isSubmitted()) {
            $request->query->add($request->query->get('consultar_retornos_cadastro'));
            $pagination = $this->get('app.retorno_cadastro_query')->search($request->query);
        }
        
        return $this->render('arquivo_retorno_cadastro/index.html.twig', [
            'form' => $form->createView(),
            'pagination' => $pagination,
        ]);
    }
    
    /**
     * 
     * @param Request $request
     * @return Response|RedirectResponse
     * 
     * @Route("arquivo-retorno-cadastro/recepcionar-arquivo", name="arquivo_retorno_cadastro_recepcionar_arquivo")
     * @Method({"GET", "POST"})
     */
    public function recepcionarArquivo(Request $request)
    {
        $command = new RecepcionarArquivoRetornoCadastroCommand();
        
        $form = $this->createForm(RecepcionarArquivoRetornoCadastroType::class, $command);
        $form->handleRequest($request);
        
        if ($form->isSubmitted()) {
            try {
                $this->getBus()->handle($command);
                $retornoCriacaoConta = $this->get('app.retorno_cadastro_query')->getLast();
                
                $btns = [
                    'Sim' => '<a href="'. $this->generateUrl('arquivo_retorno_cadastro_report', [ 'retornoCriacaoConta' => $retornoCriacaoConta->getCoSeqRetornoCriacaoConta() ]) .'">Sim</a>',
                    'Não' => '<a class="cursor-pointer" data-dismiss="alert" aria-label="Close">Não</a>',
                ];
                
                $this->addFlash('success', 'Arquivo de retorno processado com sucesso. Quantidade de participantes recepcionados: '. $retornoCriacaoConta->getQtParticipante() .'. Deseja imprimir o relatório completo do retorno recepcionado? ' . implode(' ', $btns));
                
                return $this->redirectToRoute('arquivo_retorno_cadastro');
            } catch(UnexpectedCommandBehaviorException $ub) {
                $this->addFlash('danger', $ub->getMessage());
            } catch (InvalidCommandException $ie) {
                $this->addFlashValidationError();                
            }  catch (\Exception $e) {
                $this->addFlashExecutionError();                
            }
        }
        
        return $this->render('arquivo_retorno_cadastro/recepcionar-arquivo-retorno.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    
    /**
     * 
     * @param RetornoCriacaoConta $retornoCriacaoConta
     * @return RedirectResponse
     * 
     * @Route("arquivo-retorno-cadastro/delete/{retornoCriacaoConta}", name="arquivo_retorno_cadastro_delete", options={"expose"=true})
     * @Method({"GET"})
     */
    public function delete(RetornoCriacaoConta $retornoCriacaoConta)
    {
        try {
            $retornoCriacaoConta->inativar();
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($retornoCriacaoConta);
            $em->flush();
            
            $this->addFlash('success', 'Exclusão realizada com sucesso!');
        } catch (\Exception $e) {
            $this->addFlashExecutionError();
        }
        
        return $this->redirectToRoute('arquivo_retorno_cadastro');
    }
    
    /**
     * 
     * @param RetornoCriacaoConta $retornoCriacaoConta
     * @param Request $request
     * @return Response
     * 
     * @Route("arquivo-retorno-cadastro/report/{retornoCriacaoConta}", name="arquivo_retorno_cadastro_report")
     * @Method({"GET"})
     */
    public function report(RetornoCriacaoConta $retornoCriacaoConta, Request $request)
    {
        $form = $this->createForm(FiltroRelatorioRetornoCriacaoContaType::class, null, [
            'retornoCriacaoConta' => $retornoCriacaoConta,            
        ]);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {            
            $pb = new ParameterBag($request->query->get('filtro_relatorio_retorno_criacao_conta', []));
            $tpRelatorio = FiltroRelatorioRetornoCriacaoContaType::getDescricaoTipoRelatorio($pb->get('tpRelatorio'));
            
            $now = new \DateTime();
            $report = $this->get('app.retorno_cadastro_query')->report($retornoCriacaoConta, $pb);            
            $html = $this->renderView('arquivo_retorno_cadastro/result-report.html.twig', [
                'report' => $report,
                'tpRelatorio' => $tpRelatorio,
                'stCadastro' => DicionarioCpb::getValueDescricao('SIT-CMD', $pb->get('stCadastro')),
                'formatRelatorio' => $pb->get('formatRelatorio'),
            ]);
            
            switch ($pb->get('formatRelatorio'))
            {
                case 'xls' : return $this->responseXls('relatorio-retorno-cadastro', $html);
                case 'pdf' : {                    
                    $pdFacade = $this->get('app.wkhtmltopdf_facade');
                    $pdFacade
                        ->setOption('orientation', 'Landscape')
                        ->setOption('header-right', "Página [page] de [toPage]")
                        ->setOption('margin-top', 30)
                        ->setOption('header-spacing', 15)
                        ->setOption('footer-right', 'Relatório emitido em ' . $now->format('d/m/Y H:i:s'))
                        ->setOption('footer-left', 'Responsável: ' . $this->getUser()->getUsername())
                        ->setOption('header-center', $this->renderView('arquivo_retorno_cadastro/header-report.txt.twig', [
                            'report' => $report,
                            'tpRelatorio' => $tpRelatorio,
                        ]));
                    
                    return $pdFacade->generate($html, 'relatorio-retorno-cadastro'.date('_d_m_Y'));
                }
                default : return new Response($html);
            }
        }
        
        return $this->render('arquivo_retorno_cadastro/report.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/arquivo_retorno_cadastro/header-report.txt.twig
SIGPET - {{ report.publicacao.programa.dsPrograma }}
Retorno de Remessa de Cadastro
{{ tpRelatorio }}

templates/arquivo_retorno_cadastro/index.html.twig
{% extends "base.html.twig" %}

{% block subtitle %}
    Consultar Retorno de Cadastro
{% endblock %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">Pesquisar</button>
        <a href="{{ path('arquivo_retorno_cadastro_recepcionar_arquivo') }}" class="btn btn-primary">Novo retorno</a>
    {{ form_end(form) }}
    
    {% if pagination != null and pagination.count() > 0 %}
    <hr>
    
    <table class="table table-striped margin-top-10">
        <tr>        
            <th>{{ knp_pagination_sortable(pagination, 'Data de Recepção', 'rcc.dtInclusao') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Publicaçao', 'pub.nuPublicacao') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Arquivo', 'rcc.noArquivoOriginal') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Qtde. Recepcionada', 'rcc.qtParticipante') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Qtde. de Cadastros realizados', 'rcc.qtParticipanteContaCriada') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Qtde. de Cadastros não realizados', 'rcc.qtParticipContaNaoCriada') }}</th>            
            <th>Ação</th>
        </tr>
        
        {% for rcc in pagination %}
        <tr {% if loop.index is odd %}class="color"{% endif %}>
            <td>{{ rcc.dtInclusao|date('d/m/Y') }}</td>
            <td>{{ rcc.publicacao.programa.dsPrograma ~ ' - ' ~ rcc.publicacao.tpPublicacao|publicacao ~ ' nº ' ~ rcc.publicacao.nuPublicacao ~ ' de ' ~ rcc.publicacao.dtPublicacao|date('d/m/Y') }}</td>
            <td>{{ rcc.noArquivoOriginal }}</td>
            <td>{{ rcc.qtParticipante }}</td>
            <td>{{ rcc.qtParticipanteContaCriada }}</td>
            <td>{{ rcc.qtParticipContaNaoCriada }}</td>            
            <td>
                <a href="{{ asset('uploads/' ~ rcc.noArquivoUpload) }}" download="{{ asset('uploads/' ~ rcc.noArquivoUpload) }}" class="glyphicon glyphicon-download-alt" target="_blank" title="Baixar Arquivo de Retorno"></a> 
                <a href="{{ path('arquivo_retorno_cadastro_report', { 'retornoCriacaoConta' : rcc.coSeqRetornoCriacaoConta }) }}" class="glyphicon glyphicon-list-alt" title="Imprimir relatório do Retorno de Cadastro de Conta."></a>
                <a class="glyphicon glyphicon-trash btn-remove-retorno cursor-pointer" data-id="{{ rcc.coSeqRetornoCriacaoConta }}" title="Excluir registro."></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>    
    {% elseif pagination != null and pagination.count() == 0 %}
        <hr>
        Nenhum registro encontrado.
    {% endif %}
{% endblock %}


{% block javascripts %}
    <script src="{{ asset('js/arquivo_retorno_cadastro/index.js') }}"></script>
{% endblock %}

templates/arquivo_retorno_cadastro/recepcionar-arquivo-retorno.html.twig
{% extends 'base.html.twig' %}

{% block subtitle %}
    Recepcionar novo arquivo de Retorno de Cadastro
{% endblock %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
        
        <button class="btn btn-primary" type="submit">Processar</button>
        <a href="{{ path('arquivo_retorno_cadastro') }}" class="btn btn-default">Voltar</a>
    {{ form_end(form) }}
{% endblock %}

templates/arquivo_retorno_cadastro/report.html.twig
{% extends "base.html.twig" %}

{% block subtitle %}
    Relatório do Arquivo de Retorno de Cadastro
{% endblock %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <a class="btn btn-primary" id="btn-consulta-retorno">Gerar</a>
        <a href="{{ path('arquivo_retorno_cadastro') }}" class="btn btn-default">Voltar</a>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/arquivo_retorno_cadastro/report.js') }}"></script>
{% endblock %}

templates/arquivo_retorno_cadastro/result-report.html.twig
<style type="text/css">
    table {
        border-collapse: collapse;
        width: 100%;
    }

    table, th, td {
        border: 1px solid black;
    }
    thead { display: table-header-group }
    tfoot { display: table-row-group }
    tr { page-break-inside: avoid }
</style>

{% if formatRelatorio != 'pdf' %}
<div style="text-align: center">
    <h3>SIGPET - {{ report.publicacao.programa.dsPrograma }}</h3>
    <h3>Retorno de Remessa de Cadastro do Banco do Brasil</h3>
    <h4>{{ tpRelatorio }}</h4>
</div>
{% endif %}
<hr>

<table style="margin-bottom: 20px;">
    <tr>
        <td><strong>Mês/Ano de Retorno</strong></td>
        <td>{{ report.dtInclusao|date('m/Y') }}</td>
    </tr>
    <tr>
        <td><strong>Data de recepção pelo SIGPET</strong></td>
        <td>{{ report.dtInclusao|date('d/m/Y') }}</td>
    </tr>
    <tr>
        <td><strong>Nome do arquivo de retorno</strong></td>
        <td>{{ report.noArquivoOriginal }}</td>
    </tr>
    <tr>
        <td><strong>Número do Lote</strong></td>
        <td>{{ report.cabecalhoRetornoCriacaoConta.nuSequencialLote }}</td>
    </tr>    
</table>
        
<div>
{% if stCadastro %}
    <strong>Situação do Cadastro:</strong>
    {% for key,st in stCadastro %}
         <br>{{ st|int ~ ' - ' ~ key }}
    {% endfor %}
{% endif %}
</div>
    
<table style="margin-top: 20px; width:100%; border-collapse: collapse;">
    <tr style="border-bottom: 1px solid #000;">
        <th>Participante</th>
        <th>CPF</th>
        <th>Data de Nascimento</th>
        <th>Nome da Mãe</th>
        <th>Agência</th>
        <th>Conta</th>
        <th>Posição no arquivo</th>
        <th>Ocorrência</th>
    </tr>    
    {% for detalhe in report.detalheRetornoCriacaoConta %}
        <tr>
            <td>{{ detalhe.noBeneficiario|trim }}</td>
            <td style="text-align: center;">{{ detalhe.nuCpf|cpf }}</td>
            <td style="text-align: center;">{{ detalhe.dtNascimento|date('d/m/Y') }}</td>
            <td>{{ detalhe.noMaeBeneficiario|trim }}</td>
            <td style="text-align: center;">{{ detalhe.nuIdOrgaoPagador }}</td>
            <td style="text-align: center;">{{ detalhe.nuConta }}</td>
            <td style="text-align: center;">{{ detalhe.nuSequencialRegistro|int }}</td>
            <td>{{ detalhe.stBeneficiarioPrograma == 'N' ? 'Participante não encontrado no SIGPET' : '' }}</td>
        </tr>        
    {% endfor %}
</table>

<hr>

{% if not stCadastro %}
<table>
    <tr>
        <td><strong>Quantidade Total de participantes</strong></td>
        <td>{{ report.rodapeRetornoCriacaoConta.qtRegistroDetalhe|int }}</td>
    </tr>    
</table>
{% else %}
<table>
    <tr>
        <td><strong>Quantidade de participantes da situação</strong></td>
        <td>{{ report.detalheRetornoCriacaoConta|length }}</td>
    </tr>    
</table>
{% endif %}

{% if formatRelatorio != 'pdf' %}
<hr>

<table>
    <tr>
        <td>Relatório emitido em {{ date()|date('d/m/Y H:i:s') }}</td>        
    </tr>
    <tr>
        <td>Responsável: {{ app.user.username }}</td>        
    </tr>
</table>
{% endif %}