src/Entity/Programa.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Programa
 *
 * @ORM\Table(name="DBPETINFOSD.TB_PROGRAMA")
 * @ORM\Entity(repositoryClass="App\Repository\ProgramaRepository")
 */
class Programa extends AbstractEntity
{
    use \App\Traits\DeleteLogicoTrait;
    use \App\Traits\DataInclusaoTrait;

    const AREA_ATUACAO = 1;
    const GRUPO_TUTORIAL = 2;
    
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\Column(name="CO_SEQ_PROGRAMA", type="integer")
     * @ORM\SequenceGenerator(sequenceName="DBPETINFOSD.SQ_PROGRAMA_COSEQPROGRAMA", allocationSize=1, initialValue=1)
     */
    private $coSeqPrograma;

    /**
     * @var string
     *
     * @ORM\Column(name="DS_PROGRAMA", type="string", length=255)
     */
    private $dsPrograma;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Publicacao", mappedBy="programa", cascade={"persist"})
     * @var ArrayCollection<Publicacao>
     */
    private $publicacoes;
    
    /**
     * @var string
     * 
     * @ORM\Column(name="TP_AREA_TEMATICA", type="string", length=1)
     */
    private $tpAreaTematica;

    /**
     * @var integer
     *
     * @ORM\Column(name="TP_PROGRAMA", type="integer")
     */
    private $tpPrograma;

    /**
     * Programa constructor.
     * @param $dsPrograma
     * @param $tpAreaTematica
     * @param $tpPrograma
     * @throws \Exception
     */
    public function __construct($dsPrograma, $tpAreaTematica, $tpPrograma)
    {
        $this->dsPrograma = $dsPrograma;
        $this->setTpAreaTematica($tpAreaTematica);
        $this->setTpPrograma($tpPrograma);
        $this->stRegistroAtivo = 'S';
        $this->dtInclusao = new \DateTime();
        $this->publicacoes = new ArrayCollection();
    }

    /**
     * Get coSeqPrograma
     *
     * @return int
     */
    public function getCoSeqPrograma()
    {
        return $this->coSeqPrograma;
    }

    /**
     * Get dsPrograma
     *
     * @return string
     */
    public function getDsPrograma()
    {
        return $this->dsPrograma;
    }
    
    /**
     * @return ArrayCollection<Publicacao>
     */
    public function getPublicacoes()
    {
        return $this->publicacoes;
    }
    
    /**
     * @return ArrayCollection<Publicacao>
     */
    public function getPublicacoesAtivas()
    {
        return $this->publicacoes->filter(function ($publicacao) {
            return $publicacao->isAtivo();
        });
    }

    /**
     * @param Publicacao $publicacao
     * @return Programa
     */
    public function addPublicacao(Publicacao $publicacao)
    {
        if (!$this->publicacoes->contains($publicacao)) {
            $this->publicacoes[] = $publicacao;
        }
        
        return $this;
    }

    /**
     * @param string $novoNome
     * @return Programa
     */
    public function renomear($novoNome)
    {
        $this->dsPrograma = $novoNome;
        return $this;
    }
    
    /**
     * @param integer $tpAreaTematica
     * @return Programa
     * @throws \InvalidArgumentException
     */
    public function setTpAreaTematica($tpAreaTematica)
    {
        if (!in_array($tpAreaTematica, array(1 ,2))) {
            throw new \InvalidArgumentException('Tipo de área temática inválida');
        }
        
        $this->tpAreaTematica = $tpAreaTematica;
        
        return $this;
    }

    /**
     * @param $tpPrograma
     */
    public function setTpPrograma($tpPrograma)
    {
        if (!in_array($tpPrograma, self::getTpProgramas())) {
            throw new \InvalidArgumentException('Tipo de programa inválido');
        }

        $this->tpPrograma = $tpPrograma;
    }
    
    /**
     * Get tpAreaTematica
     *
     * @return string
     */
    public function getTpAreaTematica($returnNome = false)
    {
        if ($returnNome) {
            
            $nomes = array(
                1 => 'Cursos',
                2 => 'Áreas Temáticas'
            );
            
            return $nomes[$this->tpAreaTematica];
        }
        
        return $this->tpAreaTematica;
    }

    /**
     * @return int
     */
    public function getTpPrograma()
    {
        return $this->tpPrograma;
    }

    /**
     * @return array
     */
    public static function getTpProgramas()
    {
        return array(
            'Área de Atuação' => self::AREA_ATUACAO,
            'Grupo Tutorial' => self::GRUPO_TUTORIAL,
        );
    }

    /**
     * @return bool
     */
    public function isAreaAtuacao()
    {
        return self::AREA_ATUACAO == $this->tpPrograma;
    }

    /**
     * @return bool
     */
    public function isGrupoTutorial()
    {
        return self::GRUPO_TUTORIAL == $this->tpPrograma;
    }
}

src/Controller/ProgramaController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\ParameterBag;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use League\Tactician\Bundle\Middleware\InvalidCommandException;
use App\Controller\ControllerAbstract;
use App\Form\CadastrarProgramaType;
use App\Form\AtualizarProgramaType;
use App\Form\PesquisarProgramaType;
use App\CommandBus\CadastrarProgramaCommand;
use App\CommandBus\AtualizarProgramaCommand;
use App\Entity\Programa;

/**
 * @Security("is_granted('ADMINISTRADOR')")
 */
class ProgramaController extends ControllerAbstract
{
    /**
     * @Route("/programa", name="programa")
     * @Method({"GET"})
     */
    public function allAction(Request $request)
    {
        $queryParams = $request->query->get('pesquisar_programa', array());
        $queryParams['page'] = $request->query->get('page', 1);
        
        $pagination = $this
            ->get('app.programa_query')
            ->search(
                new ParameterBag($queryParams)
            );

        $form = $this->createForm(PesquisarProgramaType::class);

        return $this->render(
            'programa/all.html.twig',
            array(
                'pagination' => $pagination,
                'queryParams' => $queryParams,
                'form' => $form->createView()
            )
        );
    }

    /**
     * @Route("/programa/cadastrar", name="programa_cadastrar")
     */
    public function cadastrarAction(Request $request)
    {
        $command = new CadastrarProgramaCommand();

        $form = $this->createForm(CadastrarProgramaType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            try {
                $this->getBus()->handle($command);
                $this->addFlash('success', 'Programa cadastrado com sucesso');

                return $this->redirectToRoute('programa');

            } catch (InvalidCommandException $e) {
                $this->addFlashValidationError();
            }
        }

        return $this->render(
            'programa/cadastrar.html.twig',
            array('form' => $form->createView())
        );
    }

    /**
     * @Route("/programa/atualizar/{programa}", name="programa_atualizar")
     */
    public function atualizarAction(Request $request, Programa $programa)
    {
        $command = new AtualizarProgramaCommand($programa);

        $form = $this->createForm(AtualizarProgramaType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            try {
                $this->getBus()->handle($command);
                $this->addFlash('success', 'Programa atualizado com sucesso');
                return $this->redirectToRoute('programa');

            } catch (InvalidCommandException $e) {
                $this->addFlashValidationError();
            }
        }

        return $this->render(
            'programa/atualizar.html.twig',
            array('form' => $form->createView(), 'programa' => $programa)
        );
    }
}

templates/programa/all.html.twig
{% extends 'base.html.twig' %}

{% block subtitle %}Pesquisar Programas{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            {{ form_start(form, {'method': 'get', attr: {'novalidate': 'novalidate'}}) }}
            {{ form_row(form.dsPrograma, {value: queryParams.dsPrograma}) }}
            <input type="submit" class="btn btn-primary" value="Pesquisar">
            <a class="btn btn-default" href="{{ path('programa_cadastrar') }}">Cadastrar Programa</a>
            {{ form_end(form) }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{{ knp_pagination_sortable(pagination, 'Programa', 'p.dsPrograma') }}</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for programa in pagination %}
                        <tr>
                            <td>{{ programa.coSeqPrograma }}</td>
                            <td>{{ programa.dsPrograma }}</td>
                            <td><a href="{{ path('programa_atualizar', {'programa': programa.coSeqPrograma}) }}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="2">Nenhum programa cadastrado.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="navigation">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
    </div>

{% endblock %}


templates/programa/atualizar.html.twig
{% extends 'base.html.twig' %}

{% block subtitle %}Atualizar Programa{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            {{ form_start(form, {'method': 'post', 'attr': {'novalidate': 'novalidate'}}) }}
                {{ form_row(form.coSeqPrograma) }}
                {{ form_row(form.dsPrograma) }}
                {{ form_row(form.tpPrograma) }}
                {{ form_row(form.tpAreaTematica) }}
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Publicações</strong></div>
                    <div class="panel-body">
                        
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Publicação</th>
                                    <th>Data de publicação</th>
                                    <th>Início vigência</th>
                                    <th>Fim vigência</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for publicacao in programa.publicacoesAtivas %}
                                    <tr>
                                        <td>{{ publicacao.tpPublicacao(true) ~ ' ' ~ publicacao.nuPublicacao }}</td>
                                        <td>{{ publicacao.dtPublicacao|date('d/m/Y') }}</td>
                                        <td>{{ publicacao.dtInicioVigencia|date('d/m/Y') }}</td>
                                        <td>{{ publicacao.dtFimVigencia|date('d/m/Y') }}</td>
                                        <td>
                                            <a href="{{ path('publicacao_atualizar', {publicacao: publicacao.coSeqPublicacao}) }}">
                                                <span class="glyphicon glyphicon-pencil" title="Editar"></span>
                                            </a>
                                            <a href="javascript:;" class="inativar-publicacao" data-coSeqPublicacao="{{ publicacao.coSeqPublicacao }}">
                                                <span class="glyphicon glyphicon-remove" title="Inativar"></span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                            
                        <a href="javascript:;" class="btn btn-default" id="nova-publicacao">Adicionar publicação</a>
                        
                        <div class="panel panel-default hidden" id="container-nova-publicacao">
                            <div class="panel-heading"><strong>Nova Publicação</strong></div>
                            <div class="panel-body">
                                {{ form_row(form.tpPublicacao) }}
                                {{ form_row(form.nuPublicacao) }}
                                {{ form_row(form.dtPublicacao, {attr: {'class': 'datepicker dmY'}}) }}
                                {{ form_row(form.dtInicioVigencia, {attr: {'class': 'datepicker dmY'}}) }}
                                {{ form_row(form.dtFimVigencia, {attr: {'class': 'datepicker dmY'}}) }}
                                {{ form_row(form.dsPublicacao) }}
                                {{ form_row(form.qtdMinimaBolsistasGrupo) }}
                                {{ form_row(form.qtdMaximaBolsistasGrupo) }}
                                <a href="javascript:;" class="btn btn-default" id="cancelar-publicacao">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a href="{{ path('programa') }}" class="btn btn-default">Voltar</a>
                <input type="submit" class="btn btn-primary" value="Salvar">
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/programa/atualizar.js') }}"></script>
{% endblock %}

templates/programa/cadastrar.html.twig
{% extends 'base.html.twig' %}

{% block subtitle %}
    Cadastrar Programa
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            {{ form_start(form, {'method': 'post', 'attr': {'novalidate': 'novalidate'}}) }}
                {{ form_row(form.dsPrograma) }}
                {{ form_row(form.tpPrograma) }}
                {{ form_row(form.tpAreaTematica) }}
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Publicação</strong></div>
                    <div class="panel-body">
                        {{ form_row(form.tpPublicacao) }}
                        {{ form_row(form.nuPublicacao) }}
                        {{ form_row(form.dtPublicacao, {attr: {'class': 'datepicker dmY'}}) }}
                        {{ form_row(form.dtInicioVigencia, {attr: {'class': 'datepicker dmY'}}) }}
                        {{ form_row(form.dtFimVigencia, {attr: {'class': 'datepicker dmY'}}) }}
                        {{ form_row(form.dsPublicacao) }}
                        {{ form_row(form.qtdMinimaBolsistasGrupo) }}
                        {{ form_row(form.qtdMaximaBolsistasGrupo) }}
                    </div>
                </div>
                <a href="{{ path('programa') }}" class="btn btn-default">Voltar</a>
                <input type="submit" class="btn btn-primary" value="Salvar">
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/programa/cadastrar.js') }}"></script>
{% endblock %}